# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  templating.engine.jade:
    class: Jade\JadeSymfonyEngine
    arguments: ["@templating.helper.assets", "@templating.helper.router"]
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
